const base = require("./eslint.config.cjs");

// Make a shallow copy and filter out any 'next/core-web-vitals' extends
// to avoid requiring Next's compiled parser in CI environments where it's unavailable.
const filtered = base.filter((item) => item !== undefined);

// Remove global extends generated by FlatCompat that include next/core-web-vitals
// (We can't introspect FlatCompat's internal arrays easily here, so provide a conservative override)
// We'll export a config that mirrors the base but without the next extends.

module.exports = filtered;
